wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1679947266.291949
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.8.10
      5: 0.13.10
      6: 4.26.1
      8:
      - 5
